name: Docker Run
description: A GitHub Action to run a docker container from private or public registries with current workspace mapped and github actions env vars available.
inputs:
  env-context:
    description: 'Pass in the workflow env context as json text. Necessary if you want env in docker without polluting docker image with host machine env vars which will cause issues.'
    required: false
  image:
    description: 'image name and tag'
    required: true
  user:
    description: 'User to run the docker image as'
    required: false
  run:
    description: 'Bash commands to run on docker image. Overrides entrypoint of docker image to /bin/bash'
    required: false
  registry:
    description: 'The private docker registry to login to'
    required: false
  username: 
    description: 'The username with which to login to the private docker registry.'
    required: false
  password: 
    description: 'The password with which to login to the private docker registry.'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
